//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class trackinfo
    {
        public int id { get; set; }
        public string uuid { get; set; }
        public string uuidfile { get; set; }
    }
}
